### ISSUE TITLE
Change license for Meshviewer to MIT

### ISSUE THREAD

**Issue by xf-** [ffrgb/meshviewer#160]
### TODO
- [x] Ask major contributors (> 5 commits)
  - [ ] Status 4/5 (contributors with combined 620 commits already agreed)
- [x] Send email to all contributors
- [ ] Agreement from all contributors with lines in current code base.

**Comment by rotanid** [comment]
is this compatible with the libraries that are required?
and why would one really need a more open license, did the requesting people specify valid reasons?

**Comment by rubo77** [comment]
I agree

**Comment by xf-** [comment]
MIT is normally more compatible then AGPL.
NodeJS/JS is MIT common license or a few BSD.

Libarys in meshviewer: MIT, BSD, BSD-2-Clause and BSD-3-Clause
https://www.bithound.io/github/ffrgb/meshviewer/develop/dependencies/npm

Build tool around Gulp + modules + Libarys
yarn licenses ls | grep 'License: MIT' | wc -l
669
From 850 (maybe few also MIT and field isn't set)

All GPL (2 dual licensed)
yarn licenses ls | grep 'GPL' -B1
├─ jschardet@1.5.1
│  ├─ License: LGPL-2.1+
--
├─ ua-parser-js@0.7.12
│  ├─ License: (GPL-2.0 OR MIT)
--
├─ ua-parser-js@0.7.14
│  ├─ License: (GPL-2.0 OR MIT)

**Comment by codedust** [comment]
I don't really understand the need for a license change. I would really be interessted in these "different reasons" from IRC.

Choosing a permissive license like MIT or BSD wouldn't really be advantageous in comparison to AGPL. The copyleft included in the AGPL makes sure, nobody distributes a commercial derivate of meshviewer under a proprietary license (without sharing the source code).

I'd also like to raise awareness for a common misinterpretation of the (A)GPL. The license does **not** forbid commercial usage of the software. It just makes sure, all modifications and improvements to meshviewer are shared with the community. E.g. the AGPL even permits a hosted "Meshviewer-as-a-Service" buisiness model (as long as all improvements of the source code are shared with the customers).

https://www.gnu.org/licenses/agpl-3.0
https://www.gnu.org/licenses/gpl-faq.html

**Comment by mdrenger** [comment]
IANAL / not a contributor either...

what codedust says: By changing from AGPL to MIT you would essentially give up on copyleft and open source - meshviewer could be distributed as closed source.

I don't think thats a good idea for a freifunk-project and i would like to stay with AGPL.

**Comment by skorpy2009** [comment]
What would be the advantage of MIT other than enhanced proprietary versions?

**Comment by xf-** [comment]
THX @mdrenger for noticing most people voting _no_ haven't one contribution to this repo. I don't care for your votes.

Contributors still have lines in current code 
-> incorrect because some code formation changes and yarn lock included
```
git summary --line

project : meshviewer
lines : 12452
authors :
11286 Xaver Maierhofer 90.6%
598 Nils Schneider 4.8%
488 Martin Geno 3.9%
18 Moorviper 0.1%
15 Moritz Warning 0.1%
13 Milan Pässler 0.1%
7 anoy 0.1%
6 Simon Joda Stößer 0.0%
5 Ruben Barkow 0.0%
3 viisauksena 0.0%
3 lemonnguyen 0.0%
2 PetaByteBoy 0.0%
2 Florian Rittmeier 0.0%
2 Florian Klink 0.0%
1 wahram 0.0%
1 PetaByteBoy // Milan Pässler 0.0%
1 Marvin W 0.0%
1 Little-Ben 0.0%
```

**Advantages:**
- Community without a vanilla ffrgb/meshviewer need to change about page and put a repo online - more fragmentation and forks. Every CSS change/ favicon.
- Similar license to used libarys - our complete base has not one AGPL license
- Still source code will be executed by client/browser

**Disadvantage**
- If somebody wants to sell it (code base is ES5 - mo modules) can do it.

**Notice:**
- Your are always allowed to fork it and develop it.
- If 

**Personal:**
I put a lot of code/work into this repo and i really don't care if somebody wants to sell it - do it. Use current version put a price tag on it or charge for setup. Anybody stupid enough to pay for it... If somebody develops a features at home and don't want it for somebody else to use it he/she can put in a library and use his library licensed under XY. I always prefer open-source software.
It looks to me as you amuse the worst in people and you want to develop with those people together.

If you want to discuss something the best place to reach me is IRC.

_I try to find the old IRC logs, no promises_

**Comment by codedust** [comment]
Sorry, I cannot really follow your argumentation.

> Community without a vanilla ffrgb/meshviewer need to change about page and put a repo online - more fragmentation and forks. Every CSS change/ favicon.

Changing the favicon or the about page does not represent a major change to the software's codebase and thus copyleft does not apply here.

> Similar license to used libarys - our complete base has not one AGPL license

I don't really see why this should be problematic in any way...

> MIT is normally more compatible then AGPL.

In fact, there is no commonly used GPL-incompatible free software licenses out there (except the MPL, if you would consider it "commonly used"). See [the GPL FAQ](https://www.gnu.org/licenses/license-list.html#GPLCompatibleLicenses) for a full list.

> Still source code will be executed by client/browser

???

> If somebody wants to sell it (code base is ES5 - mo modules) can do it.

Even AGPL code can be selled by anyone. If you business model depends on closed source software, you have no business model. ;)

Please don't misunderstand this feedback as critism of your person or your personal objections. I just wanted to raise awareness for some common misunderstandings of the AGPL.

**Comment by xf-** [comment]
Moved to internal github board
